"""close_date utcnow

Revision ID: d77c587645f5
Revises: 47ed0e1ab4ee
Create Date: 2025-04-17 08:29:19.391799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77c587645f5'
down_revision = '47ed0e1ab4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
