"""close_date timezone.utc

Revision ID: eb25ab8fee4c
Revises: d77c587645f5
Create Date: 2025-04-17 09:19:29.885202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb25ab8fee4c'
down_revision = 'd77c587645f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
